In [1]:
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [4]:
Mahasiswa = ["Rahmat Adi Nugroho", 2020071017,"INF", "DAA", "15/9/2021","UPJ"]
print(Mahasiswa)

['Rahmat Adi Nugroho', 2020071017, 'INF', 'DAA', '15/9/2021', 'UPJ']


In [2]:
bin_color= ['Red','Green','Blue','Yellow']
bin_color[1]

'Green'

In [6]:
Mahasiswa[1]

2020071017

In [7]:
Mahasiswa[5]

'UPJ'

In [22]:
bin_color[0:4]

['Red', 'Green', 'Blue', 'Yellow']

In [23]:
Mahasiswa[0:6]

['Rahmat Adi Nugroho', 2020071017, 'INF', 'DAA', '15/9/2021', 'UPJ']

In [2]:
bin_color1= ['Red','Green','Blue','Yellow']
for aColor in bin_color1:
    print( aColor + "Square" )

RedSquare
GreenSquare
BlueSquare
YellowSquare


In [17]:
Mahasiswa1 = ["Adi", "Syawal", "Aldo", "Rajwa"]
for aMahasiswa in Mahasiswa1:
    print("UPJ."+ aMahasiswa )

UPJ.Adi
UPJ.Syawal
UPJ.Aldo
UPJ.Rajwa


In [11]:
bin_colors = ('Red','Green','Blue','Yellow')
bin_colors [1]

'Green'

In [10]:
bin_colors[2:]

('Blue', 'Yellow')

In [20]:
UPJ = ("universitas","pembangunan","Jaya")
print(UPJ)

('universitas', 'pembangunan', 'Jaya')


In [21]:
nested_tuple = (100,(200,400,600),300,(400,800))
nested_tuple

(100, (200, 400, 600), 300, (400, 800))

In [24]:
nested_tuple [0]

100

In [25]:
nested_tuple [1]

(200, 400, 600)

In [26]:
nested_tuple [2]

300

In [27]:
nested_tuple [3]

(400, 800)

In [28]:
bin_colors = {"manual_color":"Yellow", "approved_color":"Green","refused_color":"Red"}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [30]:
bin_colors.get('manual_color')

'Yellow'

In [32]:
bin_colors['approved_color']

'Green'

In [33]:
bin_colors['approved_color']='Purple'
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [35]:
biodata ={"Nama":"Rahmat Adi Nugroho","NIM":2020071017,"Prodi":"Informatika","Universitas":"UPJ"}
print(biodata)

{'Nama': 'Rahmat Adi Nugroho', 'NIM': 2020071017, 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [36]:
biodata.get('Nama')

'Rahmat Adi Nugroho'

In [37]:
biodata['Prodi']

'Informatika'

In [39]:
Green = {'Grass','Leaves'}
print(Green)

{'Leaves', 'Grass'}


In [40]:
Green = {'Grass','Leaves','Leaves','Grass'}
print(Green)

{'Leaves', 'Grass'}


In [42]:
yellow = {'dandelions', 'leaves', 'fire hydrant'}
red = {'rose','blood','leaves','fire hydrant' }

yellow|red

{'blood', 'dandelions', 'fire hydrant', 'leaves', 'rose'}

In [43]:
yellow&red

{'fire hydrant', 'leaves'}

In [44]:
import pandas as pd
df = pd.DataFrame([['1','Fares',32,True],['2','Elena',23,False],['3','Steven',40,True]])


In [45]:
print(df)

   0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True


In [50]:
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [51]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [52]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [53]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [54]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [55]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [62]:
mhs=pd.DataFrame([['informatika',50,30,20],['Sistem Informasi',55,30,25],['Teknik Sipil', 40,30,10]])

In [64]:
mhs

0   1   2   3
0       informatika  50  30  20
1  Sistem Informasi  55  30  25
2      Teknik Sipil  40  30  10

In [65]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [66]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [86]:
Matrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(Matrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


In [3]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [4]:
stack = Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [5]:
print(stack.pop())

Yellow


In [6]:
print(stack.isEmpty())

False


In [7]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [8]:
queue =  Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [9]:
print(queue.dequeue())

Red


In [10]:
print(queue.dequeue())

Green
